version: '3.8'

services:
  temporal:
    image: temporalio/auto-setup:1.22
    environment:
      - DB=postgresql
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-db
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    ports:
      - "7233:7233" # Temporal frontend
    depends_on:
      - temporal-db

  temporal-ui:
    image: temporalio/ui:2.15.0
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - "8080:8080"
    depends_on:
      - temporal

  temporal-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
    ports:
      - "5432:5432"
    volumes:
      - temporal-db-data:/var/lib/postgresql/data

  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    ports:
      - "2379:2379"
    volumes:
      - milvus-etcd-data:/etcd

  milvus-minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - milvus-minio-data:/data

  milvus:
    image: milvusdb/milvus:v2.3.9
    command: ["milvus", "run", "standalone"]
    environment:
      - ETCD_ENDPOINTS=milvus-etcd:2379
      - MINIO_ADDRESS=milvus-minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - DATA_PATH=/var/lib/milvus/data
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - milvus-etcd
      - milvus-minio
    volumes:
      - milvus-data:/var/lib/milvus

volumes:
  temporal-db-data:
  milvus-etcd-data:
  milvus-minio-data:
  milvus-data: 